### ISSUE TITLE
No module named 'ols'

### ISSUE THREAD

**Issue by DvP17** [bryangraham/ipt#2]
When importing ipt in python 3.9.6 I get the following error message:

```
>>> import ipt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\site-packages\ipt\__init__.py", line 10, in <module>
    from ols import ols
ModuleNotFoundError: No module named 'ols'
```

I have installed ipt via pip. Do I need to install another module before?

Kind regards

**EDIT:** Ok, it worked when I cloned the repository, as described on your website (http://bryangraham.github.io/econometrics/causal/inference/2016/05/15/IPT-module.html)

**Comment by bryangraham** [comment]
Hi. The module was last checked on Python 3.6. Likely a backwards compatibility issue of some type. ols.py is in the repo, but parts of this code-based are over five years old, so you'll likely have to work with an older version of python and/or do some debugging/updating to get this work. In theory I'll update the codebase at some point, but it is low priority right now. Of course I'd be delighted if someone else took on the project! The core algorithmic part is solid; just all the Python window dressed that is dated and needs updating. Take care. -Bryan

**Comment by DvP17** [comment]
Thank you very much for your reply! I just wondered a little bit since the description in the python package index is "ipt: a Python 2.7 package". So when cloning this repo and not using pip everything worked fine. Unfortunately, my primary language is R and my python knowledge is more basic. Therefore, I could rather help to port the package and netrics to R. But right now I'm still busy with understanding your work and article on dyadic regression from 2019 and your script https://github.com/bryangraham/short_courses/blob/master/St_Gallen/2020/Notebooks/Notebook_3_Dyadic_Regression.ipynb (especially, how to include the year there if you have panel data). Best regards!

**Comment by bryangraham** [comment]
Thanks for noting the dated title. Pooling multiple time periods together is conceptually straightforward, but I am pretty certain you'll need to make some changes to standard error computation. Definitely on the "to do" list, but bandwidth on my end is scarce right now. I am sure others would appreciate an R and/or Stata implementation. Take care and good luck!
